### ISSUE TITLE
running 'make all'  on CentOS  fails to compile

### ISSUE THREAD

**Issue by Nheyer** [ComparativeGenomicsToolkit/sonLib#9]
I checked out the repository, then after running 
`make all ` I get the following errors 
: 
`g++ -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 
g++: fatal error: no input files
compilation terminated.
make: *** [../../sonLib/lib/sonLib.a] Error 1
`
it seems like some sort of issue with the make files 
I am having to make from source because I do not have root access on the server and a compilation is needed for 'hal'

**Comment by diekhans** [comment]
this looks like you do not have sonLib pre-compiled in the required adjacent
directory, so some rule in hal is trying to build it.

HAL is also available pre-compiled in the binary cactus distribution

**Comment by Nheyer** [comment]
I am trying to compile sonLib directly as per the instructions in the HAL and directly invoking make to create the above mentioned sonLib binaries when I am getting this error. I am attempting to convert a hal file into vg format for viewing, but cactus dosn't include  hal2paf or seqwish ( why I am installing HAL )

**Comment by diekhans** [comment]
the master branch compiles find for me on centos 7.0

try just removing it an checking it out again.

if that does not fix it, please *attach* the output of

   make -d

**Comment by Nheyer** [comment]
I just (re)tried that and no success here is both the standard error output and standard output 
[LOG_STDOUT.txt](https://github.com/ComparativeGenomicsToolkit/sonLib/files/4887804/LOG_STDOUT.txt)
[LOG_STDERR.txt](https://github.com/ComparativeGenomicsToolkit/sonLib/files/4887806/LOG_STDERR.txt)

**Comment by diekhans** [comment]
this is very weird

This implies that in 
  sonLib/C/Makefile

this isn't set:
  cppSources = impl/*.cpp

would you run it again, with -p instead of -d?

**Comment by Nheyer** [comment]
here you go, I am running this on UCSC's courtyard server by the way 

[LOG_STDERR-ran_with_p.txt](https://github.com/ComparativeGenomicsToolkit/sonLib/files/4887929/LOG_STDERR-ran_with_p.txt)
[LOG_STDOUT-ran_with_p.txt](https://github.com/ComparativeGenomicsToolkit/sonLib/files/4887931/LOG_STDOUT-ran_with_p.txt)

**Comment by diekhans** [comment]
> here you go, I am running this on UCSC's courtyard server by the way 

Ah!  well, I was about to say, I can't debug this remotely, can't you
talk to a local make expert.

well, I guess that is me!!

mail me at markd@ucsc.edu and we will figure out how to connect
by slack or something

**Comment by Nheyer** [comment]
For anyone getting the same issue down the line this ended up being caused by a  "\n" in the environment variable CXX_ABI_DEF ,  make sure this is not the case
